import Head from "next/head";
// import Image from "next/image";
import type { NextPage } from "next";
import { Box, Heading, Text, Image, VStack } from "@gluestack-ui/themed";
import { useEffect, useState } from "react";
import ClientSDK from "@project/client-sdk";
// https://picsum.photos/v2/list
const fetchUsers = async () => {
  const res = await ClientSDK.dbclient?.user.findMany();
  return res;
};
const Meta = () => {
  return (
    <Head>
      <title>Create Gluestack App</title>
      <meta name="description" content="Generated by node glue add web" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
const Grid = ({ children }: any) => {
  return (
    <Box justifyContent="center" flexDirection="row" flexWrap="wrap" gap={"$10"}>
      {children}
    </Box>
  );
};
const Container = ({ data }: any) => {
  return (
    <Box
      flex={1}
      bg="$white"
      p="$10"
      alignItems="center"
      sx={{
        _web: { minHeight: "100vh" },
      }}
    >
      <Heading size="3xl" mb="$12" textAlign="center" color="$amber500" fontFamily="Homemade Apple">React India Github Book</Heading>
      <Grid>
        {data && data.map((item: any) => (
          <VStack
            space="lg"
            justifyContent="center"
            alignItems="center"
            w="350px"
            bg="$amber50"
            py="$12"
            rounded={8}
            borderWidth={2}
            borderStyle="dashed"
            borderColor="$amber400"
          >
            <Box overflow="hidden" borderRadius={"$full"} w="200px">
              <img
                src={item.githubAvatarUrl}
                alt="Picture of the author"
              />
            </Box>
            <Heading color="$amber400" fontFamily="Homemade Apple">
              {item.name}
            </Heading>
            <Box w="100%" px="$8">
              <Text color="$amber400" fontFamily="monospace">
                Github: {item.githubId}
              </Text>
              {item.content ? <Text color="$amber400" fontFamily="Homemade Apple">
                <Text color="$amber400" fontFamily="monospace" >Feelings:</Text> {item.content}
              </Text> : <Text color="$amber400" fontFamily="Homemade Apple">
                <Text color="$amber400" fontFamily="monospace" >Feelings:</Text> Too busy to share them :|
              </Text>}
              {item.emailId && <Text color="$amber400" fontFamily="Homemade Apple">
                <Text color="$amber400" fontFamily="monospace" >You can reach me on:</Text> {item.emailId}
              </Text>}
            </Box>
          </VStack>
        ))}
        {/* <Box w="350px" p="$10" bg="$amber400"></Box> */}
      </Grid>
    </Box>
  );
};

const Home: NextPage = () => {
  let [data, setData] = useState([]);

  useEffect(() => {
    fetchUsers().then((data) => setData(data));
  }, []);
  return (
    <div>
      <Meta />
      <Container data={data} />
    </div>
  );
};

export default Home;
