import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Button, ButtonText, Input, InputField } from "@gluestack-ui/themed";
import ClientSDK from "@project/client-sdk";
import { useState } from "react";

const Meta = () => {
  return (
    <Head>
      <title>Create Gluestack App</title>
      <meta name="description" content="Generated by node glue add web" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};



const Example = () => {

  const [name, setName] = useState("");
  const [githubId, setGithubId] = useState("");

  function handleUpload(event: any) {
    console.log(name, githubId)
  }



  return (
    <div className={styles.container}>
      <div className={styles.gradient}>
        <Image src="/gradient.svg" alt="Gradient" fill priority />
      </div>
      <main className={styles.main}>
        <p className={styles.badge}>
          Get started by editing <code>pages/index.tsx</code>
        </p>
        <Input
          variant="outline"
          size="md"
          isDisabled={false}
          isInvalid={false}
          isReadOnly={false}
        >
          <InputField color={"$white"} value={name} onChange={(e: any) => {
            setName(e.target.value);
          }} placeholder="Enter Name here" />
        </Input>
        <Input
          variant="outline"
          size="md"
          isDisabled={false}
          isInvalid={false}
          isReadOnly={false}
        >
          <InputField color={"$white"} value={githubId} onChange={(e: any) => {
            setGithubId(e.target.value);
          }} placeholder="Enter Github here" />
        </Input>
        <button onClick={handleUpload}>Upload File</button>

        <div className={styles.logo}>
          <Image src="/logo.svg" fill alt="logo" priority />
        </div>

      </main>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.parent}>
      <Meta />
      <Example />
    </div>
  );
};

export default Home;
